version: '3.9'

services:
  api:
    container_name: snippet-api-${ENVIRONMENT}
    #image: ghcr.io/ingsis-team/snippet-service-2025:${ENVIRONMENT}
    build:
      context: .
    ports:
      - "${API_PORT}:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PERMISSION_URL: ${PERMISSION_URL}
      PRINTSCRIPT_URL: ${PRINTSCRIPT_URL}
      ASSET_URL: api:8080
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH_SERVER_URI: ${AUTH_SERVER_URI}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_MANAGEMENT_TOKEN: ${AUTH0_MANAGEMENT_TOKEN}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${AUTH_SERVER_URI}
      # New Relic configuration
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      # Inyectar agente en JVM
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    volumes:
      - ./newrelic:/newrelic
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - permission-service-2025_default
      - printscript-service-2025_default
      - asset-service_default

  db:
    container_name: snippet-db-${ENVIRONMENT}
    image: postgres:17
    ports:
      - "${DB_HOST_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    name: postgres_data_${ENVIRONMENT}

networks:
  default:
  permission-service-2025_default:
    external: true
  printscript-service-2025_default:
    external: true
  asset-service_default:
    external: true
